### PR TITLE
add messaging section

### PR DESCRIPTION
**Pull request by acoburn**
Here is something to get started.

### CODE REVIEW

**Comment by awoods** [comment]
This looks great, @acoburn. 
My only question is whether we want to split this guide into multiple documents (e.g. messaging.md, resource-management.md, resource-versioning.md, etc) or take the approach of the specification itself by having a single document.

**Comment by acoburn** [comment]
@awoods I had that same question (whether to have multiple sections), and I don't have an answer. My thinking was that the first priority was to get the content in place, and then figure out the organization as appropriate. Which is to say, I'm not at all wedded to this structure.

**Comment by awoods** [comment]
@acoburn ... we can revisit the structure question later.

**Comment by birkland** [comment]
This looks great!  I'm going to add a few issues for adding in some prose describing some behavior of the current Fedora implementation that may be worth mentioning.  Not sure when I'll be able to get to them, but don't want to forget

**Pull request merged**
